"""
==============================================================================
PYTHON TYPE CLASSES REFERENCE: dataclass vs Pydantic vs TypedDict
==============================================================================

QUICK DECISION GUIDE:
┌─────────────────┬──────────────────────────────────────────────────────┐
│ Use TypedDict   │ You only need type hints for dicts (no behavior)     │
│ Use dataclass   │ You need a clean class with methods + auto __init__  │
│ Use Pydantic    │ You need runtime validation + serialization (APIs)   │
└─────────────────┴──────────────────────────────────────────────────────┘

INSTALL:
    pip install pydantic       # Pydantic is NOT built-in
    # dataclasses, TypedDict  → built-in (no install needed)
"""

# ==============================================================================
# 1. TypedDict  — just a typed dictionary, no behavior
# ==============================================================================
"""
- It IS a dict under the hood — no class magic, no methods
- Type hints only: Python does NOT enforce them at runtime
- Use when you're passing around dicts and want IDE/mypy support
- total=False makes ALL keys optional; use Required/NotRequired for fine control
"""

from typing import TypedDict, Required, NotRequired

class UserDict(TypedDict):
    id: int
    name: str
    email: str

class PartialUserDict(TypedDict, total=False):
    # total=False → all keys become optional
    id: int
    name: str
    email: str

class MixedUserDict(TypedDict):
    id: Required[int]        # must be present
    name: Required[str]      # must be present
    email: NotRequired[str]  # optional

# --- Usage ---
user: UserDict = {"id": 1, "name": "Alice", "email": "alice@example.com"}

# TypedDict IS just a dict — all dict operations work
print(user["name"])          # Alice
print(user.get("email"))     # alice@example.com
print(type(user))            # <class 'dict'>  ← it's literally a dict

# NO runtime enforcement — this won't raise an error at runtime!
bad_user: UserDict = {"id": "not-an-int", "name": 123, "email": None}  # type: ignore
print("TypedDict does NOT validate:", bad_user)

# Useful pattern: function that expects a typed dict
def greet_user(user: UserDict) -> str:
    return f"Hello, {user['name']}!"

print(greet_user(user))


# ==============================================================================
# 2. dataclass  — auto-generated class with __init__, __repr__, __eq__
# ==============================================================================
"""
- A regular Python class with boilerplate auto-generated by @dataclass
- Type hints are used to generate __init__ — but NOT enforced at runtime
- Supports default values, default_factory, post_init hooks, and more
- Can add your own methods freely
- frozen=True makes it immutable (and hashable)
"""

from dataclasses import dataclass, field, asdict, astuple
from typing import ClassVar

@dataclass
class Product:
    # Required fields (no default) MUST come before optional ones
    id: int
    name: str
    price: float

    # Optional fields with defaults
    in_stock: bool = True
    tags: list[str] = field(default_factory=list)  # ← NEVER use [] as default directly

    # ClassVar is NOT included in __init__ — it's a class-level variable
    _category: ClassVar[str] = "general"

    # Called automatically AFTER __init__
    def __post_init__(self):
        if self.price < 0:
            raise ValueError(f"Price cannot be negative: {self.price}")
        self.name = self.name.strip().title()   # normalize name

    # Custom method — totally fine
    def apply_discount(self, percent: float) -> float:
        return round(self.price * (1 - percent / 100), 2)

    def __str__(self):
        return f"Product({self.id}: {self.name} @ ${self.price})"


# --- Usage ---
p1 = Product(id=1, name="  laptop  ", price=999.99, tags=["electronics"])
p2 = Product(id=2, name="mouse", price=29.99)

print(p1)                          # Product(1: Laptop @ $999.99)
print(repr(p1))                    # auto-generated __repr__
print(p1 == Product(1, "Laptop", 999.99, tags=["electronics"]))  # True — value equality

print(p1.apply_discount(10))       # 899.99

# Convert to dict / tuple
print(asdict(p1))                  # {'id': 1, 'name': 'Laptop', ...}
print(astuple(p1))                 # (1, 'Laptop', 999.99, True, ['electronics'])

# __post_init__ validation fires
try:
    bad = Product(id=3, name="bad", price=-5.0)
except ValueError as e:
    print("dataclass __post_init__ caught:", e) # Raises because we have post_init validation

# dataclass also does NOT enforce types at runtime
no_error = Product(id="not-an-int", name="oops", price=40)  # type: ignore
print("dataclass allows wrong types:", no_error)


# Frozen dataclass — immutable + hashable (can be used in sets/dicts)
@dataclass(frozen=True)
class Point:
    x: float
    y: float

    def distance_from_origin(self) -> float:
        return (self.x ** 2 + self.y ** 2) ** 0.5

p = Point(3.0, 4.0)
print(p.distance_from_origin())    # 5.0
print(hash(p))                     # hashable because frozen=True

try:
    p.x = 10  # type: ignore
except Exception as e:
    print("Frozen dataclass caught:", e)


# ==============================================================================
# 3. Pydantic  — runtime validation + serialization
# ==============================================================================
"""
- Like dataclass but WITH actual runtime type enforcement
- Coerces types when possible (e.g. "42" → 42 for an int field)
- Raises ValidationError with clear messages for invalid data
- Built-in JSON serialization (.model_dump(), .model_dump_json())
- Best choice for: API inputs/outputs, config loading, data pipelines
"""

from pydantic import BaseModel, Field, field_validator, model_validator, EmailStr
from typing import Optional
from datetime import date

class Address(BaseModel):
    street: str
    city: str
    zip_code: str

class Employee(BaseModel):
    id: int
    name: str
    email: str                              # basic string — won't validate format
    salary: float = Field(gt=0)            # Field: must be > 0
    department: str = "Engineering"        # default value
    hire_date: date = Field(default_factory=date.today)
    address: Optional[Address] = None      # nested model, optional
    skills: list[str] = []

    # Validator on a single field
    @field_validator("name")
    @classmethod
    def name_must_not_be_empty(cls, v: str) -> str:
        v = v.strip()
        if not v:
            raise ValueError("Name cannot be empty")
        return v.title()                    # normalize

    # Validator across multiple fields
    @model_validator(mode="after")
    def check_senior_salary(self) -> "Employee":
        if "senior" in self.name.lower() and self.salary < 80_000:
            raise ValueError("Senior employees must earn at least $80,000")
        return self

# --- Usage ---
emp = Employee(
    id=1,
    name="  alice smith  ",
    email="alice@company.com",
    salary=95_000,
    address={"street": "123 Main St", "city": "NYC", "zip_code": "10001"},  # dict → model!
    skills=["Python", "SQL"]
)

print(emp)
print(emp.name)            # Alice Smith  ← normalized by validator
print(emp.address.city)    # NYC  ← nested model, not a dict

# Pydantic DOES coerce compatible types
coerced = Employee(id="42", name="Bob", email="b@b.com", salary="75000.0")  # type: ignore
print(type(coerced.id))       # <class 'int'>  ← "42" became 42
print(type(coerced.salary))   # <class 'float'>

# Validation errors are clear and structured
from pydantic import ValidationError

try:
    bad_emp = Employee(
        id=2,
        name="",             # fails name validator
        email="x@x.com",
        salary=-500          # fails Field(gt=0)
    )
except ValidationError as e:
    print("\nPydantic ValidationError:")
    for err in e.errors():
        print(f"  Field: {err['loc']} | Error: {err['msg']}")

# Serialization — great for APIs
print("\nmodel_dump():", emp.model_dump())
print("\nJSON:", emp.model_dump_json(indent=2))

# Create modified copy without mutating
emp2 = emp.model_copy(update={"salary": 105_000})
print("\nOriginal salary:", emp.salary)    # 95000
print("Copied salary:  ", emp2.salary)    # 105000


# ==============================================================================
# SIDE-BY-SIDE COMPARISON
# ==============================================================================
"""
Feature                  TypedDict        dataclass        Pydantic
─────────────────────────────────────────────────────────────────────
Built-in (no install)    ✅               ✅               ❌
Is actually a dict       ✅               ❌               ❌
Runtime validation       ❌               ❌               ✅
Type coercion            ❌               ❌               ✅
Custom methods           ❌               ✅               ✅
__init__ auto-gen        ❌ (it's dict)   ✅               ✅
__repr__ auto-gen        ❌               ✅               ✅
__eq__ auto-gen          ❌ (dict eq)     ✅               ✅
Immutable option         ❌               frozen=True      model_config
JSON serialization       ❌               manual/json lib  .model_dump_json()
Nested model support     ❌               manual           ✅ auto
IDE / mypy support       ✅               ✅               ✅
Best for                 Typed dicts      Clean classes    APIs / validation
"""